services:
  - type: web
    name: easycheck-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: "20"